//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOut
    {
        public int Id { get; set; }
        public int BookID { get; set; }
        public int ReaderID { get; set; }
        public int LibraryID { get; set; }
        public System.DateTime CheckOutDate { get; set; }
    }
}
