//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace website
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class favlEntities : DbContext
    {
        public favlEntities()
            : base("name=favlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<Librarian> Librarians { get; set; }
        public virtual DbSet<Library> Libraries { get; set; }
        public virtual DbSet<Reader> Readers { get; set; }
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<CheckOut> CheckOuts { get; set; }
        public virtual DbSet<CheckOutsByDay> CheckOutsByDays { get; set; }
    
        public virtual int UpdateCheckOutsByDay(Nullable<System.DateTime> dayEnd)
        {
            var dayEndParameter = dayEnd.HasValue ?
                new ObjectParameter("dayEnd", dayEnd) :
                new ObjectParameter("dayEnd", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UpdateCheckOutsByDay", dayEndParameter);
        }
    }
}
